### ISSUE TITLE
Update brand context for spacing on heading sizes

### ISSUE THREAD

**Issue by foxintherain** [springernature/frontend-toolkits#767]
### What

Following a review of the new global forms component, line height on heading, text labels and micro-copy are inconsistent and need updating. 

### Why

We also need a consistent approach to spacing for margins across brands to improve our designs.

### Done when

- [x] Updated the brand context with styling changes for headings and spacing
- [x] Reviewed by @foxintherain and @sturobson  / @Heydon 
- [x] Update sketch styleguide to reflect any changes

### Details for line height and typography:
https://www.sketch.com/s/fa9c2fc9-a179-43f0-b21e-9562c9c17c0c/a/3OrPQ3r

**Comment by Heydon** [comment]
> Following a review of the new global forms component, line height on heading, text labels and micropy are inconsistent and need updating.

For clarity, we need to fix/update this at the brand(s) level, right? Not just in `global-forms`? Line-heights seem excessively large in nature and springernature, by default.

**Comment by foxintherain** [comment]
@Heydon Correct, this needs to be at brand level and then filter down to components.

**Comment by sturobson** [comment]
I thought I had added it to the big [Design Tokens todo list](https://github.com/springernature/frontend-toolkits/issues/763) so that it's separated from the `global-forms` release candidate work and would become part of a future major breaking change to `brand-context`.

**Comment by foxintherain** [comment]
Agreed with @Heydon  that we will also add margins to the different heading sizes to help with spacing:

**Top Margin spacing:**

- 32px: for H3  H4 and H5 Titles
- 48px: for H2 Title

**And if we also wanted to add bottom Margin:**

- 8px AfterH2 , H3 , H4 titles and H5 titles
- 16px: After the H1 titles and paragraphs

**Comment by foxintherain** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15365576/181588912-0c4ab5f1-ea71-45cb-9b10-b0a46cc39cfc.png">

**Comment by Heydon** [comment]
Some thoughts and questions as I do this (cc: @foxintherain @sturobson):

* The springer brand overrides some basic default brand heading styling already, so I feel like this needs to be done in the springer brand. This is probably the same for nature and springernature. 
* I feel like I'm supposed to use the `spacing()` function but not sure if this translates to `rems`?
* We can't just add `h2 {margin-top: spacing(4)` (for example) because this will apply the margin where it is the first element and it's unnecessary. I think we should be using the `* + h2` construct?
* I'm not sure about adding bottom margin. Ideally, all flow content margin should be either top or bottom margin. Top is preferred so we can do the `* + x` construct imo?

**Comment by sturobson** [comment]
It feels like this is pushing more towards the `c-content` for content and leaving the base `h1`-`h6` with not margins, letting the component they're in define the values.

> I feel like I'm supposed to use the spacing() function but not sure if this translates to rems

Yeah, the [spacing function](https://github.com/springernature/frontend-toolkits/blob/master/context/brand-context/default/scss/20-functions/spacing.scss) returns `N * 1px` so it's a pixel value. If it's a 'content component' it could/would come from tokens?

> 'm not sure about adding bottom margin. Ideally, all flow content margin should be either top or bottom margin.

I think this is fine for a specific 'long form content component' for articles, etc. I wholly agree with a `* + x` stack layout for any other components.
